# Generated by Django 2.0.12 on 2019-05-07 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '主商品SPU', 'verbose_name_plural': '主商品SPU'},
        ),
        migrations.AlterModelOptions(
            name='goodssku',
            options={'verbose_name': '子商品SKU', 'verbose_name_plural': '子商品SKU'},
        ),
        migrations.AddField(
            model_name='goodssku',
            name='shelf',
            field=models.CharField(default='001', max_length=48, verbose_name='货架号'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='spu_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='主SPU号'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='主商品SPU'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='sku_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='子商品SKU'),
        ),
    ]
