# Generated by Django 2.0.12 on 2019-05-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190507_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='g_url',
            field=models.CharField(default='', max_length=400, verbose_name='商品链接'),
        ),
    ]
