# Generated by Django 2.0.12 on 2019-05-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20190522_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['spu_id'], 'verbose_name': '主商品SPU', 'verbose_name_plural': '主商品SPU'},
        ),
        migrations.AddField(
            model_name='goodssku',
            name='th_sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='泰国售价'),
        ),
    ]
