# Generated by Django 2.0.12 on 2019-06-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20190527_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodssku',
            name='status',
            field=models.BooleanField(default=1, verbose_name='商品状态'),
        ),
    ]
