# Generated by Django 2.0.12 on 2019-05-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190507_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='customer_info',
            field=models.CharField(default='100%/0', max_length=32, verbose_name='客户收货率'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='receiver',
            field=models.CharField(default='默认', max_length=32, verbose_name='收件人'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_status',
            field=models.SmallIntegerField(choices=[(1, '待发货'), (2, '已发货'), (3, '已完成')], default=1, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品总额'),
        ),
    ]
