# Generated by Django 2.0.12 on 2019-05-19 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20190516_2226'),
        ('order', '0005_auto_20190516_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('count', models.IntegerField(default=1, verbose_name='商品数量')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='采购价格')),
            ],
            options={
                'verbose_name': '采购单商品',
                'verbose_name_plural': '采购单商品',
                'db_table': 'purchase_goods',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('purchase_id', models.CharField(max_length=16, unique=True, verbose_name='采购单号')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='采购总额')),
                ('desc', models.CharField(max_length=128, verbose_name='备注')),
                ('pur_status', models.SmallIntegerField(choices=[(1, '采购中'), (2, '已入库')], default=1, verbose_name='采购状态')),
            ],
            options={
                'verbose_name': '采购单',
                'verbose_name_plural': '采购单',
                'db_table': 'purchase_order',
            },
        ),
        migrations.AddField(
            model_name='purchasegoods',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.PurchaseOrder', verbose_name='采购单'),
        ),
        migrations.AddField(
            model_name='purchasegoods',
            name='sku_good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSKU', verbose_name='商品SKU'),
        ),
    ]
