# Generated by Django 2.0.12 on 2019-05-27 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20190519_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['purchase_id'], 'verbose_name': '采购单', 'verbose_name_plural': '采购单'},
        ),
    ]
