# Generated by Django 2.0.12 on 2019-06-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20190605_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='order_shopeeid',
            field=models.CharField(default='', max_length=16, verbose_name='平台订单号'),
        ),
    ]
