# Generated by Django 2.0.12 on 2019-06-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_orderinfo_order_shopeeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_status',
            field=models.SmallIntegerField(choices=[(1, '待发货'), (2, '已发货'), (3, '已完成'), (4, '已处理'), (5, '已打单')], default=1, verbose_name='订单状态'),
        ),
    ]
