# Generated by Django 2.0.12 on 2019-06-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20190617_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_status',
            field=models.SmallIntegerField(choices=[(1, '待发货'), (2, '待打包'), (3, '已完成'), (4, '已处理'), (5, '已打单')], default=1, verbose_name='订单状态'),
        ),
    ]
