# Generated by Django 2.0.12 on 2019-07-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20190617_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasegoods',
            name='status',
            field=models.BooleanField(default=0, verbose_name='入库状态'),
        ),
    ]
