# Generated by Django 2.0.12 on 2019-07-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_purchasegoods_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='desc',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='备注'),
        ),
    ]
