# Generated by Django 2.0.12 on 2019-07-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20190707_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='order_desc',
            field=models.CharField(default='nothing', max_length=128, verbose_name='订单备注'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='desc',
            field=models.CharField(default='nothing', max_length=128, verbose_name='备注'),
        ),
    ]
