# Generated by Django 2.0.12 on 2019-07-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20190713_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_desc',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='订单备注'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='备注'),
        ),
    ]
