# Generated by Django 2.0.12 on 2019-11-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20190905_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='order_pay_time',
            field=models.CharField(blank=True, default='-', max_length=16, verbose_name='拨款时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_country',
            field=models.CharField(choices=[('MYR', '马来西亚'), ('PHP', '菲律宾'), ('THB', '泰国'), ('IDR', '印尼'), ('SGD', '新加坡'), ('BRL', '巴西'), ('TWD', '台湾')], default='MYR', max_length=5, verbose_name='订单国家'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_status',
            field=models.SmallIntegerField(choices=[(1, '待发货'), (2, '待打包'), (3, '已完成'), (4, '已处理'), (5, '已打单'), (6, '已拨款'), (7, '异常款')], default=1, verbose_name='订单状态'),
        ),
    ]
