# Generated by Django 2.0.12 on 2020-07-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20191214_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_country',
            field=models.CharField(choices=[('MYR', '马来西亚'), ('PHP', '菲律宾'), ('THB', '泰国'), ('IDR', '印尼'), ('SGD', '新加坡'), ('BRL', '巴西'), ('TWD', '台湾'), ('VND', '越南')], default='MYR', max_length=5, verbose_name='订单国家'),
        ),
    ]
