# Generated by Django 2.0.12 on 2021-07-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_auto_20210614_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='order_package_num',
            field=models.CharField(default='', max_length=32, verbose_name='包裹号码'),
        ),
    ]
