# Generated by Django 2.0.12 on 2021-07-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_auto_20210702_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='order_waybill_num',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='运单号码'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_package_num',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='包裹号码'),
        ),
    ]
